### ISSUE TITLE
[BUG] Doesn't parse multiple array elements correctly within a Properties section - only works if all are false

### ISSUE THREAD

**Issue by n1t1nv3rma** [aws-cloudformation/cloudformation-guard#100] opened 2020-11-11 00:44 UTC
**Describe the bug**
CFN guard doesn't parse multiple array elements correctly within a Properties section - only works if all are false

If 1st element is correct but 2nd element is correct, then check => end result is PASS. <== EXPECTED
If 1st element is correct but 2nd element is wrong, then check => end result is PASS. **<== NOT EXPECTED**
If 1st element is wrong but 2nd element is correct, then check => end result is PASS. **<== NOT EXPECTED**
If 1st element is wrong but 2nd element is wrong, then check => end result is FAIL (listing both errors). <== EXPECTED

Even though the actual individual test shows correct results, the overall failure does not occur until all values fail. 

**BONUS:** We can't even rely on exit codes. Exit code is always 0.

**To Reproduce**

**TEMPLATE:**
```yaml
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "AWS CloudFormation Sample Template for CFN guard.",
  "Resources": {
    "InstanceSecurityGroup" : {
      "Type" : "AWS::EC2::SecurityGroup",
      "Properties" : {
         "GroupDescription" : "Allow http to client host",
         "VpcId" : {"Ref" : "myVPC"},
         "SecurityGroupIngress" : [{
            "IpProtocol" : "tcp",
            "FromPort" : 80,
            "ToPort" : 80,
            "CidrIp" : "0.0.0.0/0"
         },
         {
          "IpProtocol" : "tcp",
          "FromPort" : 443,
          "ToPort" : 443,
          "CidrIp" : "0.0.0.0/0"
        }],
         "SecurityGroupEgress" : [{
            "IpProtocol" : "-1",
            "FromPort" : 0,
            "ToPort" : 65535,
            "CidrIp" : "10.0.0.0/0"
         }]
      }
    }
  }
}
```

**RULESET:**
```
let ingress_allowed_ports = [80, 443]
AWS::EC2::SecurityGroup WHEN SecurityGroupIngress.\*.CidrIp.\* == 0.0.0.0/0 CHECK SecurityGroupIngress.\*.FromPort IN %ingress_allowed_ports << Ingress EC2 Security Groups opened to the 0.0.0.0 from Ports other than 80 or 443 are not allowed without security approval.
```

**RESULTS:**

PASS:
```bash
$ cfn-guard check -r cfn-guard-bug.ruleset -t cfn-guard-bug.json -vvv | egrep -i "pass|fail"
2020-11-11 11:30:26,438 INFO  [cfn_guard] Result: PASS
2020-11-11 11:30:26,438 INFO  [cfn_guard] Result: PASS
2020-11-11 11:30:26,438 TRACE [cfn_guard] pass_fail set is {"pass"}
2020-11-11 11:30:26,438 INFO  [cfn_guard] Result: PASS
2020-11-11 11:30:26,439 INFO  [cfn_guard] Result: PASS
2020-11-11 11:30:26,439 TRACE [cfn_guard] pass_fail set is {"pass"}
2020-11-11 11:30:26,439 TRACE [cfn_guard] pass_fail set is {}
2020-11-11 11:30:26,439 INFO  [cfn_guard] All CloudFormation resources passed

$ echo $?
0
```

** CHANGE only 1st RULE TO FAIL: DOES NOT WORK AS EXPECTED **
```yaml
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "AWS CloudFormation Sample Template for CFN guard.",
  "Resources": {
    "InstanceSecurityGroup" : {
      "Type" : "AWS::EC2::SecurityGroup",
      "Properties" : {
         "GroupDescription" : "Allow http to client host",
         "VpcId" : {"Ref" : "myVPC"},
         "SecurityGroupIngress" : [{
            "IpProtocol" : "tcp",
            "FromPort" : 81,
            "ToPort" : 81,
            "CidrIp" : "0.0.0.0/0"
         },
         {
          "IpProtocol" : "tcp",
          "FromPort" : 443,
          "ToPort" : 443,
          "CidrIp" : "0.0.0.0/0"
        }],
         "SecurityGroupEgress" : [{
            "IpProtocol" : "-1",
            "FromPort" : 0,
            "ToPort" : 65535,
            "CidrIp" : "10.0.0.0/0"
         }]
      }
    }
  }
}
```
**RESULTS:**
```bash
$ cfn-guard check -r cfn-guard-bug.ruleset -t cfn-guard-bug.json -vvv | egrep -i "pass|fail"
2020-11-11 11:31:10,501 INFO  [cfn_guard] Result: PASS
2020-11-11 11:31:10,501 INFO  [cfn_guard] Result: PASS
2020-11-11 11:31:10,501 TRACE [cfn_guard] pass_fail set is {"pass"}
2020-11-11 11:31:10,501 INFO  [cfn_guard] Result: PASS
2020-11-11 11:31:10,502 INFO  [cfn_guard] Result: FAIL
2020-11-11 11:31:10,502 TRACE [cfn_guard] temp_results are ["[InstanceSecurityGroup] failed because [SecurityGroupIngress.0.FromPort] is [81] and Ingress EC2 Security Groups opened to the 0.0.0.0 from Ports other than 80 or 443 are not allowed without security approval."]
2020-11-11 11:31:10,502 TRACE [cfn_guard] pass_fail set is {"pass", "fail"}
2020-11-11 11:31:10,502 TRACE [cfn_guard] pass_fail set is {}
2020-11-11 11:31:10,502 INFO  [cfn_guard] All CloudFormation resources passed

$ echo $?
0
```

** CHANGE only 2nd RULE TO FAIL: DOES NOT WORK AS EXPECTED **
```yaml
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "AWS CloudFormation Sample Template for CFN guard.",
  "Resources": {
    "InstanceSecurityGroup" : {
      "Type" : "AWS::EC2::SecurityGroup",
      "Properties" : {
         "GroupDescription" : "Allow http to client host",
         "VpcId" : {"Ref" : "myVPC"},
         "SecurityGroupIngress" : [{
            "IpProtocol" : "tcp",
            "FromPort" : 80,
            "ToPort" : 80,
            "CidrIp" : "0.0.0.0/0"
         },
         {
          "IpProtocol" : "tcp",
          "FromPort" : 1443,
          "ToPort" : 1443,
          "CidrIp" : "0.0.0.0/0"
        }],
         "SecurityGroupEgress" : [{
            "IpProtocol" : "-1",
            "FromPort" : 0,
            "ToPort" : 65535,
            "CidrIp" : "10.0.0.0/0"
         }]
      }
    }
  }
}
```
**RESULTS:**
```bash
$ cfn-guard check -r cfn-guard-bug.ruleset -t cfn-guard-bug.json -vvv | egrep -i "pass|fail"
2020-11-11 11:32:14,127 INFO  [cfn_guard] Result: PASS
2020-11-11 11:32:14,127 INFO  [cfn_guard] Result: PASS
2020-11-11 11:32:14,127 TRACE [cfn_guard] pass_fail set is {"pass"}
2020-11-11 11:32:14,127 INFO  [cfn_guard] Result: PASS
2020-11-11 11:32:14,128 INFO  [cfn_guard] Result: FAIL
2020-11-11 11:32:14,128 TRACE [cfn_guard] temp_results are ["[InstanceSecurityGroup] failed because [SecurityGroupIngress.1.FromPort] is [1443] and Ingress EC2 Security Groups opened to the 0.0.0.0 from Ports other than 80 or 443 are not allowed without security approval."]
2020-11-11 11:32:14,128 TRACE [cfn_guard] pass_fail set is {"pass", "fail"}
2020-11-11 11:32:14,128 TRACE [cfn_guard] pass_fail set is {}
2020-11-11 11:32:14,128 INFO  [cfn_guard] All CloudFormation resources passed

$ echo $?
0
```

** CHANGE BOTH TO FAIL: BOTH WORK AS EXPECTED **
```bash
$ cfn-guard check -r cfn-guard-bug.ruleset -t cfn-guard-bug.json -vvv | egrep -i "pass|fail"
2020-11-11 11:33:53,525 INFO  [cfn_guard] Result: PASS
2020-11-11 11:33:53,525 INFO  [cfn_guard] Result: PASS
2020-11-11 11:33:53,525 TRACE [cfn_guard] pass_fail set is {"pass"}
2020-11-11 11:33:53,526 INFO  [cfn_guard] Result: FAIL
2020-11-11 11:33:53,526 INFO  [cfn_guard] Result: FAIL
2020-11-11 11:33:53,526 TRACE [cfn_guard] temp_results are ["[InstanceSecurityGroup] failed because [SecurityGroupIngress.1.FromPort] is [1443] and Ingress EC2 Security Groups opened to the 0.0.0.0 from Ports other than 80 or 443 are not allowed without security approval.", "[InstanceSecurityGroup] failed because [SecurityGroupIngress.0.FromPort] is [81] and Ingress EC2 Security Groups opened to the 0.0.0.0 from Ports other than 80 or 443 are not allowed without security approval."]
2020-11-11 11:33:53,526 TRACE [cfn_guard] pass_fail set is {"fail"}
2020-11-11 11:33:53,526 TRACE [cfn_guard] pass_fail set is {}
    "[InstanceSecurityGroup] failed because [SecurityGroupIngress.0.FromPort] is [81] and Ingress EC2 Security Groups opened to the 0.0.0.0 from Ports other than 80 or 443 are not allowed without security approval. when AWS::EC2::SecurityGroup SecurityGroupIngress.*.CidrIp.* == 0.0.0.0/0",
    "[InstanceSecurityGroup] failed because [SecurityGroupIngress.1.FromPort] is [1443] and Ingress EC2 Security Groups opened to the 0.0.0.0 from Ports other than 80 or 443 are not allowed without security approval. when AWS::EC2::SecurityGroup SecurityGroupIngress.*.CidrIp.* == 0.0.0.0/0",
**[InstanceSecurityGroup] failed because [SecurityGroupIngress.0.FromPort] is [81] and Ingress EC2 Security Groups opened to the 0.0.0.0 from Ports other than 80 or 443 are not allowed without security approval. when AWS::EC2::SecurityGroup SecurityGroupIngress.*.CidrIp.* == 0.0.0.0/0
[InstanceSecurityGroup] failed because [SecurityGroupIngress.1.FromPort] is [1443] and Ingress EC2 Security Groups opened to the 0.0.0.0 from Ports other than 80 or 443 are not allowed without security approval. when AWS::EC2::SecurityGroup SecurityGroupIngress.*.CidrIp.* == 0.0.0.0/0
Number of failures: 2**

echo $?
0
```
**Expected behavior**
Expect multiple array elements in Properties section to work irrespective of the one or more bad entry.

**Screenshots**
NA

**Operating System:**
MacOS 

**OS Version**
Mojave, 10.14.6

**Additional context**

**Comment by n1t1nv3rma** [comment] 2020-11-11 00:55
Also, try changing "CidrIp" to get unexpected results.

**Comment by jotompki** [comment] 2020-11-11 21:27
Having a bit of trouble interpreting your ruleset. CidrIp should not have a wildcard after it correct? The wildcard oeprator is used to iterate over arrays. For single values of keys you should just be able to refer to the CidrIp as such:
```
AWS::EC2::SecurityGroup WHEN SecurityGroupIngress.*.CidrIp == 0.0.0.0/0
```

**Comment by RyanSchaefer** [comment] 2020-12-11 20:17
@jotompki I figured I would comment on this because I am having a similar issue and I wanted to hopefully clarify what the issue is.

It seems many people are trying to preform this logic on lists in cloud formation: if a condition is met in this list, for the matching item, determine if it passes a condition or fails.

So for example I have the ruleset:
```
AWS::EC2::SecurityGroup WHEN SecurityGroupIngress.*.FromPort == 22 CHECK SecurityGroupIngress.*.CidrIp != 0.0.0.0/0
AWS::EC2::SecurityGroup WHEN SecurityGroupIngress.*.FromPort == 22 CHECK SecurityGroupIngress.*.CidrIpv6 != ::/0
```

What I am trying to say with this is:

when some item in the list has a port 22 open check THAT item if it is open to the world. 

Instead it appears the best we can currently express with the language as it is written is:    

when some item in the list has a port 22 open check if any item in the list contains something open to the world.

Here is an MCVE:
```
  VPC:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: {Ref: VPC}
      GroupDescription: ""
      SecurityGroupIngress:
        - Decription: "should fail"
          IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - Decription: "should fail"
          IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIpv6: ::/0
        - Decription: "should pass"
          IpProtocol: TCP
          FromPort: 80
          ToPort: 22
          CidrIpv6: ::/0
      Tags:
        - Key: Name
          Value: {"Fn::Sub": "${AWS::StackName}-SHARED-LINK"}
```

All three of course fail here for the reason outlined above. CFN-Guard finds that there is a rule with FromPort == 22 and also finds a a CidrIpv6: ::/0 even if those aren't on the same item.

What this language needs is someway of capturing an offending item and using it in another rule. Any easy way to emulate this might be to expand the existing object comparison for json objects to allow partial matches so I could say `SecurityGroupIngress.* NOT_LIKE {"ToPort": 22, "CidrIpv6" "::/0"}` and it would fail if for each key present in the checked object, it matched the actual object.

**Comment by jotompki** [comment] 2021-01-22 00:45
This is related to #107 as well, where the resource satisfies the condition because one item in the resource's array of properties satisfies the condition, then it attempts to check all items in the resource against the same check, even if some items do not match the condition. As of now there isn't a solution for this, but be on the lookout for an RFC for language additions similar to #111 that will allow for this in a subsequent release. We are attempting to add more advanced filtering in a given resource to check for conditions like this that involve nested arrays with multiple items, some of which may satisfy a check.

**Comment by jotompki** [comment] 2021-01-22 00:46
Closing and going to track status in #107, as this exemplifies the same issue.

**Closed by jotompki** 2021-01-22 00:46 UTC
Labels: bug
