### ISSUE TITLE
[BUG] Unable to parse inline json string during AWS Config rule evaluation

### ISSUE THREAD

**Issue by pavlobarvinko** [aws-cloudformation/cloudformation-guard#295] opened 2022-11-02 10:22 UTC
I am using the CloudFormation guard to evaluate the AWS resource compliance using custom AWS Config rules.
The rule gets the so-called ConfigurationItem as input. This ConfigurationItem is a json structure, describing AWS resource in question. I am particularly interested in evaluating elements of the resource policy. This policy is a json structure on itself, embedded in the ConfigurationItem structure as an escaped string. The example of such ConfigurationItem for S3 bucket  - supplementaryConfiguration.BucketPolicy.policyText - is shown below (many not relevant fields are skipped for brevity):
```
{
  "version": "1.3",
  "resourceType": "AWS::S3::Bucket",
  "supplementaryConfiguration": {
    "BucketPolicy": {
      "policyText": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"DenyReducedReliabilityStorage\",\"Effect\":\"Deny\",\"Principal\":\"*\",\"Action\":\"s3:*\",\"Resource\":\"arn:aws:s3:::s3-test-pbarvinko/*\",\"Condition\":{\"StringEquals\":{\"s3:x-amz-storage-class\":[\"ONEZONE_IA\",\"REDUCED_REDUNDANCY\"]}}}]}"
    },
    "IsRequesterPaysEnabled": true,
    "BucketVersioningConfiguration": {
      "status": "Enabled",
      "isMfaDeleteEnabled": null
    }
  }
}
```
When I try to evaluate the value of Statement[*].Effect in this inline policy, cfn-guard cannot do it, because supplementaryConfiguration.BucketPolicy.policyText is a string.
I have found a very old issue - https://github.com/aws-cloudformation/cloudformation-guard/issues/11 - talking about similar problem when using CF yaml with the embedded json. Unfortunately the proposed there solution also does not work. cfn-guard reports parsing error 
```
Parsing error handling rule file = s3-reduced-reliability-is-not-used.guard, Error = Parser Error when parsing Parsing Error Error parsing file s3-reduced-reliability-is-not-used.guard at line 5 at column 35, when handling , fragment .BucketPolicy.*
        {
            policyText|Version == "1"
        }
    }
```
What is the right way to parse and evaluate elements of the inline json structure in this case?

I am on the MacOS BigSur 11.7.1, using cfn-guard 2.1.0.

Thank you.

**Comment by razcloud** [comment] 2022-11-04 01:11
Thank you @pavlobarvinko We'll take a look at this with the team and get back to you.

**Comment by joshfried-aws** [comment] 2022-11-08 21:50
Hi @pavlobarvinko can you please share the exact rule that you are trying to evaluate? So we can look into this further. 

Thanks, 
Josh

**Comment by pavlobarvinko** [comment] 2022-11-09 14:22
@joshfried-aws I do not have a complete rule yet as I bumped into the parsing issue immediately after started writing it.
The idea is to evaluate Statements inside the BucketPolicy, searching for a policy, which denies all s3 actions when s3:x-amz-storage-class is either ONEZONE_IA or REDUCED_REDUNDANCY.
The boiler plate would be like this:
```
rule check_s3_reduced_reliability_storage_is_not_used when 
    resourceType == "AWS::S3::Bucket" 
    {
        supplementaryConfiguration.BucketPolicy.policyText exists

        supplementaryConfiguration.BucketPolicy.policyText.Statement[*]
        {
            Effect == "Deny"
        }
    }
```

**Comment by razcloud** [comment] 2022-11-11 14:58
Hi @pavlobarvinko, We are still looking into this issue.  At this point in time, this is an enhancement request and not a bug.

**Comment by fabiodouek** [comment] 2023-02-17 14:28
+1 on this. We need an intrinsic function to convert from string to a JSONobject. Without it, I can't really evaluate Resource Policies.

**Comment by joshfried-aws** [comment] 2023-06-08 19:45
Hi @pavlobarvinko  and @fabiodouek #361 addresses this issue. This feature will be available on our next release.

I am going to go ahead and close this ticket. 

Feel free to reopen if need be!

Thanks,

**Closed by joshfried-aws** 2023-06-08 19:45 UTC
Labels: enhancement, yellow
